### ISSUE TITLE
font-size:inherit break rt tag

### ISSUE THREAD

**Issue by yumetodo** [GitbookIO/theme-default#36]
```md
「・・・<ruby>本気<rt>ほんき</rt></ruby>で？」  
「<ruby>本気<rt>マジ</rt></ruby>で」
```

when I wrote such markdown and build gitbook, 

![tmp](https://cloud.githubusercontent.com/assets/10869046/19999837/e792825c-a2b7-11e6-9166-09f0135e45e9.png)

font-size of ``<rt>`` become very big!(the font-size of ``ほんき`` is same as the font-size of ``本気``)

```css
.markdown-section * {
	box-sizing:border-box;
	-webkit-box-sizing:border-box;
	font-size:inherit
}
```

``font-size:inherit`` cause this. However, I cannot detect which lsss file produce this line.
